[tox]
envlist =
    ruff
    mypy
    test

[testenv]
runner = uv-venv-lock-runner
package = skip
dependency_groups =
    dev
    test
commands =
    coverage run -m pytest tests/ --junitxml="junittest.xml" -v
    coverage report -m --fail-under 90
    coverage xml

[testenv:ruff]
description = run ruff linter and formatter
dependency_groups = dev
commands =
    ruff format
    ruff check

[testenv:mypy]
description = run mypy type checker
dependency_groups = dev
commands =
    mypy .

[coverage:run]
relative_files = True
source = open_source_polarion_python_repo_template/
branch = True
