[tox]
isolated_build = True
envlist =
    ruff
    mypy
    test

[testenv:ruff]
description = run ruff linter and formatter
allowlist_externals = uv
setenv =
    UV_PROJECT_ENVIRONMENT={envdir}
commands_pre =
    uv sync --group dev --frozen
commands =
    uv run --frozen ruff format
    uv run --frozen ruff check
[testenv:mypy]
description = run mypy type checker
allowlist_externals = uv
setenv =
    UV_PROJECT_ENVIRONMENT={envdir}
commands_pre =
    uv sync --group dev --frozen
commands =
    uv run --frozen mypy .

[testenv]
description = run pytest and coverage
allowlist_externals = uv
setenv =
    UV_PROJECT_ENVIRONMENT={envdir}
commands_pre =
    uv sync --group dev --group test --frozen
commands =
    uv run --frozen coverage run -m pytest tests/ --junitxml="junittest.xml" -v
    uv run --frozen coverage report -m --fail-under 90
    uv run --frozen coverage xml

[coverage:run]
relative_files = True
source = open_source_polarion_python_repo_template/
branch = True
