---
name: Build & Release
on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
jobs:
  verify-with-tox:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 📄 Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: 🧱 Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: 🧱 Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
        with:
          python-version: '3.14'
          cache: poetry
      - name: 🧱 Install dependencies
        run: poetry install --all-extras
      - name: 🧪 Run tests
        run: poetry run tox
      - name: SonarCloud scan for PR
        uses: sonarsource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602  # v6.0.0
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
      - name: SonarCloud scan for Push
        uses: sonarsource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602  # v6.0.0
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.branch.name=${{ github.head_ref }}
  release-please:
    needs: verify-with-tox
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.ref_name == 'main'
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: 🚀 release-please
        id: release
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38  # v4.4.0
        with:
          release-type: python
          include-v-in-tag: false
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
  build-and-publish:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    permissions:
#      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing for PyPI
      contents: write  # Required for uploading artifacts to GitHub release
    steps:
      - name: 📄 Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: 🧱 Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: 🧱 Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
        with:
          python-version: '3.14'
          cache: poetry
      - name: 🧱 Install dependencies
        run: poetry install
      - name: 📦 Build the package
        run: poetry build
      - name: 📦 Publish artifacts to GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_VERSION: needs.release-please.outputs.version
        run: gh release upload "${RELEASE_VERSION}" dist/*.{tar.gz,whl}
#      - name: 📦 Publish artifacts to PyPI/TestPyPI
#        env:
#          name: testpypi
#          url: https://test.pypi.org/p/python-requirements-inspector
#          name: pypi
#          url: https://pypi.org/p/python-requirements-inspector
#        uses: pypa/gh-action-pypi-publish@release/v1.12.3
#        with:
#          repository-url: https://test.pypi.org/legacy/  # it must be removed when publishing to PyPI
#          verbose: true
